//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFSR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LFSR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 2 1 0
        ///3 3 2 0
        ///4 4 3 0
        ///5 5 3 0
        ///6 6 5 0
        ///7 7 6 0
        ///8 8 6 4 0
        ///9 7 4 2 0
        ///10 6 5 2 0
        ///11 8 5 2 0
        ///12 7 4 3 0
        ///13 9 7 3 0
        ///14 9 7 2 0
        ///15 11 6 3 0
        ///16 10 7 4 0
        ///17 12 8 4 0
        ///18 15 9 4 0
        ///19 13 9 4 0
        ///20 13 9 5 0
        ///21 17 11 5 0
        ///22 16 12 5 0
        ///23 17 11 5 0
        ///24 20 11 5 0
        ///25 18 12 6 0
        ///26 17 13 6 0
        ///27 20 13 7 0
        ///28 21 15 7 0
        ///29 20 14 8 0
        ///30 20 13 8 0
        ///31 23 15 7 0
        ///32 25 15 7 0
        ///33 25 16 8 0
        ///34 24 15 7 0
        ///35 27 17 8 0
        ///36 25 17 8 0
        ///37 28 18 9 0
        ///38 28 20 9 0
        ///39 28 18 9 0
        ///40 29 21 10 0
        ///41 29 19 10 0
        ///42 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Taps {
            get {
                return ResourceManager.GetString("Taps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.jjj.de/mathdata/.
        /// </summary>
        internal static string Taps_credit {
            get {
                return ResourceManager.GetString("Taps_credit", resourceCulture);
            }
        }
    }
}
